# Generated by Django 3.0.4 on 2020-04-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlersgroup_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobemployee',
            name='date_end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobemployee',
            name='date_start',
            field=models.DateField(blank=True),
        ),
    ]
